# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='footerrequest',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='footerrequest',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
